<?php

/**
 * @file
 * Contains breema_migrate.module.
 */

use CommerceGuys\Addressing\Country\CountryRepositoryInterface;

/**
 * Migration callback function to map country names to country codes.
 */
function breema_migrate_map_country_to_code($source_country) {
  static $country_map = array();
  if (empty($country_map)) {
    $country_repository = \Drupal::service('address.country_repository');
    $country_map = $country_repository->getList();
    $country_map = array_map('strtolower', $country_map);
  }

  if (empty($source_country)) {
    return 'US';
  }
  return array_search(strtolower($source_country), $country_map);
}

/**
 * Migration callback function to handle Instructor certification fields.
 */
function breema_migrate_certification($source) {
  // By default, all entries are certified practitioners.
  $certification = ['practitioner'];
  if ($source != '---') {
    // If *any* of the instructor certification columns are set, turn on
    // Self-Breema instructor.
    $certification[] = 'inst-self-breema';
    // Now, see if either provisional or full instructor are set:
    $source_certifications = explode('-', $source);
    if (!empty($source_certifications[2]) || !empty($source_certifications[3])) {
      $certification[] = 'inst-breema';
    }
  }
  return $certification;
}

/**
 * Migration callback function to set roles based on certification fields.
 */
function breema_migrate_map_certification_to_roles($source) {
  // By default, all entries are certified practitioners.
  $roles = ['practitioner'];
  if ($source != '---') {
    // If *any* of the instructor certification columns are set that's enough.
    $roles[] = 'instructor';
  }
  return $roles;
}

/**
 * Migration callback function to set filename based on file path.
 */
function breema_migrate_image_path_to_uri($source) {
  // $source will be something like 'bodywork/SA_AL.jpg'.
  $file_parts = explode('/', $source);
  return 'public://image/' . $file_parts[0] . '/2018-01/' . $file_parts[1];
}

/**
 * Migration callback function to set image type based on file path.
 */
function breema_migrate_image_path_to_type($source) {
  $base = dirname($source);
  switch ($base) {
    case 'self-breema':
      return 'Self-Breema';
    case 'social_media':
      return 'Social Media';
    default:
      return ucfirst($base);
  }
}
