module:
  action: 0
  address: 0
  admin_toolbar: 0
  advanced_text_formatter: 0
  audiofield: 0
  auto_entitylabel: 0
  automated_cron: 0
  block: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  ckeditor_blockquote_attribution: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  datetime_extras: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  duration_field: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entityqueue: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  fixed_text_link_formatter: 0
  flag: 0
  flexslider: 0
  flexslider_fields: 0
  forward: 0
  fullcalendar_view: 0
  gcontent_field: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  gnode: 0
  google_analytics: 0
  group: 0
  group_notify: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  link: 0
  login_emailusername: 0
  media: 0
  menu_block: 0
  menu_trail_by_path: 0
  menu_ui: 0
  node: 0
  options: 0
  override_node_options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  queue_mail: 0
  quickedit: 0
  r4032login: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  responsive_menu: 0
  rest: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  smart_trim: 0
  smtp: 0
  social_media_links: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_responsive_search: 0
  tour: 0
  update: 0
  user: 0
  variationcache: 0
  video_embed_field: 0
  video_embed_media: 0
  view_unpublished: 0
  views_contextual_filters_or: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  breema: 100
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  breema2: 0
  sevenbreema: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
