_core:
  default_config_hash: nxSrDLfGrYXfq31BHWTA8e--X4HfLSVGF_8lJkB3CHA
langcode: en
forward_form_title: 'Forward this page'
forward_form_noindex: false
forward_max_recipients: 1
forward_form_instructions: ''
forward_form_allow_plain_text: false
forward_form_display_page: true
forward_form_display_subject: false
forward_form_display_body: false
forward_personal_message: 0
forward_personal_message_filter: false
forward_personal_message_tags: 'p,br,em,strong,cite,code,ul,ol,li,dl,dt,dd'
forward_form_confirmation: 'Thank you for spreading the word about [site:name]!'
forward_email_logo: ''
forward_email_from_address: website@breema.com
forward_email_subject: '[forward:sender-name] has forwarded a page to you from [site:name]'
forward_email_message: '[forward:sender-name] thought you would like to see this page from [site:name] web site.'
forward_email_footer: ''
forward_bypass_access_control: 0
forward_filter_format_html: ''
forward_filter_format_plain_text: ''
forward_flood_control_limit: 10
forward_flood_control_error: 'You can''t send more than @number messages per hour. Please try again later.'
forward_entity_node: true
forward_view_full: false
forward_view_teaser: false
forward_interface_type: link
forward_interface_title: 'Forward this page'
forward_interface_weight: 0
forward_link_inline: 1
forward_link_title: 'Forward this page'
forward_link_icon: ''
forward_link_style: 0
forward_link_noindex: true
forward_link_nofollow: false
forward_node_article: true
forward_node_directory_entry: true
forward_node_essence: true
forward_node_event: true
forward_node_page: true
forward_node_place: true
forward_node_product: true
