_core:
  default_config_hash: L1NLZHorv0hiCyXT83hfpLptiTWHi9nsKNYnDMcMVDg
queue_mail_keys: 'group_notify_*'
queue_mail_queue_time: 30
queue_mail_queue_wait_time: 2
threshold: 50
requeue_interval: 10800
