smtp_on: true
smtp_host: sub3.mail.dreamhost.com
smtp_hostbackup: ''
smtp_port: '465'
smtp_protocol: ssl
smtp_username: breema-website@dwwright.net
smtp_password: 
smtp_from: breema-website@dwwright.net
smtp_fromname: 'Breema Center Website'
smtp_client_hostname: sub3.mail.dreamhost.com
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
