<?php

/**
 * @file
 * Contains breema.module.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\StringTranslation\PluralTranslatableMarkup;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;
use Drupal\user\UserInterface;
use Drupal\views\Views;
use Drupal\views\ViewExecutable;
use Drupal\views\ResultRow;

use Drupal\breema\BreemaEventMgr;
use Drupal\flag\Entity\Flagging;

/**
 * Implements hook_help().
 */
function breema_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the breema module.
    case 'help.page.breema':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom code for www.breema.com') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function breema_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'breema/global';
}

/**
 * Implements hook_preprocess_html().
 */
function breema_preprocess_html(&$variables) {
  // Work-around the bugs from https://www.drupal.org/node/953034
  // For now, hard-code that anonymous users on /directory* should not see the
  // sidebar.
  if (empty($variables['logged_in'])) {
    switch ($variables['root_path']) {
      case 'directory':
      case 'search':
        unset($variables['page']['sidebar_first']);
        break;
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for nodes.
 *
 * Calls out to bundle-specific functions.
 */
function breema_preprocess_node(&$variables) {
  if (substr($variables['view_mode'], 0, 6) == 'teaser') {
    // Our teasers are generally constructed to make the entire article (the
    // containing tag) a link, so we need to strip most HTML from whatever is
    // being rendered in here. Preserve cosmetic HTML, but remove links and
    // embedded entities.
    foreach ($variables['content'] as $field_name => $field) {
      if (!empty($variables['content'][$field_name][0]['#text'])) {
        breema_strip_links($variables['content'][$field_name][0]['#text']);
      }
    }
  }

  switch ($variables['node']->getType()) {
    case 'event':
      breema_preprocess_node_event($variables);
      break;

    case 'product':
      breema_preprocess_node_product($variables);
      break;

  }
}

/**
 * Preprocess function for event nodes.
 *
 * Special handling for field_parent_event and field_subtitle on schedule nodes.
 * If there are required hours, cleanup how that is displayed.
 * Magic for rendering info about instructors (e.g. as links to directory
 * entries).
 */
function breema_preprocess_node_event(&$variables) {
  if (!empty($variables['node']->get('field_parent_event')->getValue())) {
    $variables['content']['field_subtitle']['#access'] = FALSE;
  }
  if ($variables['view_mode'] == 'full') {
    if (!empty($variables['content']['field_parent_event'][0])) {
      $variables['content']['field_parent_event']['#title'] = t('Part of the');
    }
    if (!empty($variables['content']['field_required_hours'][0])) {
      $hours = $variables['node']->field_required_hours->get(0)->value;
      if (!empty($hours)) {
        $variables['content']['field_required_hours'] = [
          '#type' => 'markup',
          '#prefix' => '<div class="field-name-field-required-hours>',
          '#markup' => new PluralTranslatableMarkup($hours, '1 class hour required.', '@hours class hours required.', ['@hours' => $hours]),
          '#suffix' => '</div>',
          '#weight' => $variables['content']['field_required_hours']['#weight'],
        ];
      }
      else {
        $variables['content']['field_required_hours']['#access'] = FALSE;
      }
    }
  }
  if (!empty($variables['content']['field_instructors'])) {
    $instructors = $variables['node']->get('field_instructors')->referencedEntities();
    if (!empty($instructors)) {
      $instructor_label = count($instructors) == 1 ? t('Instructor') : t('Instructors');
      $label_callback = $variables['view_mode'] == 'full' ? 'breema_entity_label_instructor_directory_entry' : 'breema_entity_label_plain';
      $variables['content']['field_instructors'] = [
        '#type' => 'markup',
        '#prefix' => '<div>',
        // Using the normal plural formatting class (PluralTranslatableMarkup)
        // auto-sanitizes and breaks our links. So we manually check the count
        // and do this "raw". This would be broken for RTL languages, but we
        // won't worry about that for now.
        '#markup' => $instructor_label . ': ' . breema_get_entity_label_multiple($instructors, $label_callback),
        '#suffix' => '</div>',
        '#weight' => isset($variables['content']['field_instructors']['#weight']) ? $variables['content']['field_instructors']['#weight'] : 0,
      ];
      // If we're on the 'full' view of an event, conditionally inject
      // instructor bios.
      if ($variables['view_mode'] == 'full' && !empty($variables['node']->get('field_display_instructor_bios')->value)) {
        $variables['content']['instructor_bios'] = [
          '#type' => 'container',
          '#weight' => 100,
          'header' => [
            '#weight' => -10,
            '#prefix' => '<h2>',
            '#markup' => $instructor_label,
            '#suffix' => '</h2>',
          ],
        ];
        $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
        foreach ($instructors as $instructor) {
          $directory_entries = $instructor->get('field_directory_entry')->referencedEntities();
          if (!empty($directory_entries)) {
            $directory_entry = array_pop($directory_entries);
            $variables['content']['instructor_bios'][$instructor->id()] = $view_builder->view($directory_entry, 'teaser_compact');
          }
          else {
            $variables['content']['instructor_bios'][$instructor->id()] = [
              '#markup' => '<h3>' . $instructor->label() . '</h3>',
            ];
          }
        }
      }
    }
  }
}

/**
 * Preprocess function for product nodes.
 *
 * Looks up and injects the 'Buy now' link from the 1st product info paragraph
 * into the 'compact teaser' of the main product itself.
 */
function breema_preprocess_node_product(&$variables) {
  if ($variables['view_mode'] == 'teaser_compact') {
    $all_product_info = $variables['node']->get('field_product_info')->referencedEntities();
    // Always use the first / top product info paragraph for 'Buy now' link.
    $buy_now_link = $all_product_info[0]->get('field_buy_now')->getValue();
    $variables['content']['buy_now'] = [
      '#type' => 'link',
      '#title' => t('Buy now'),
      '#url' => Url::fromUri($buy_now_link[0]['uri']),
      '#prefix' => '<div class="field--name-field-buy-now">',
      '#suffix' => '</div>',
    ];
    $variables['#attached']['library'][] = 'breema/store';
  }
}

/**
 * Implements hook_preprocess_HOOK() for file bundle media entities.
 */
function breema_preprocess_media__file(&$variables) {
  if (substr($variables['view_mode'], 0, 5) == 'view_') {
    $variables['content']['field_media_file'][0]['#description'] = $variables['content']['name'][0]['#context']['value'];
    $variables['content']['name']['#access'] = FALSE;
  }
}

/**
 * Preprocess function for blocks.
 */
function breema_preprocess_block(&$variables) {
  if ($variables['plugin_id'] == 'views_block:breema_events_featured-block_list') {
    $variables['content']['actions'] = _breema_get_more_events_action_links();
  }
}

/**
 * Preprocess function for users.
 *
 * If the user has a directory entry, hide the (now duplicate) user_picture.
 */
function breema_preprocess_user(&$variables) {
  if (!empty($variables['user']->get('field_directory_entry')->getValue())) {
    $variables['content']['user_picture']['#access'] = FALSE;
  }
}

/**
 * Preprocess function for fields.
 */
function breema_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_product') {
    $variables['attributes']['class'][] = 'grid--container';
    $variables['attributes']['class'][] = 'grid--container-1-2';
  }
  if ($variables['element']['#field_name'] == 'field_media_3') {
    $variables['attributes']['class'][] = 'grid--container';
    $variables['attributes']['class'][] = 'grid--container-1-3';
  }
}

/**
 * Preprocess function for all paragraphs.
 *
 * If the paragraph defines 'field_header_text', wrap it in h2.
 */
function breema_preprocess_paragraph(&$variables) {
  if (!empty($variables['content']['field_header_text'])) {
    $variables['content']['field_header_text']['#prefix'] = '<h2>';
    $variables['content']['field_header_text']['#suffix'] = '</h2>';
  }
  if ($variables['paragraph']->hasField('field_link')) {
    $link = $variables['paragraph']->get('field_link')->getValue();
    if (!empty($link)) {
      $url = Url::fromUri($link[0]['uri']);
      $variables['url'] = $url->toString();
    }
  }
}

/**
 * Preprocess function for 'Featured events' paragraph type.
 *
 * Injects the map and list displays of the 'breema_events_featured' view.
 * Converts field_header_text into an h2.
 * Injects links to the /events/* pages (calendar, map + search).
 */
function breema_preprocess_paragraph__event_featured(&$variables) {
  $display = 'block_list';
  $view = Views::getView('breema_events_featured');
  $view->setDisplay($display);
  $view->execute();
  if (count($view->result)) {
    $variables['content'][$display] = $view->preview($display);
  }
  $variables['content']['actions'] = _breema_get_more_events_action_links();
}

/**
 * Preprocess function for 'Person' paragraph type.
 *
 * Injects list of upcoming events (if any).
 */
function breema_preprocess_paragraph__person(&$variables) {
  $user_entities = $variables['paragraph']->get('field_person')->referencedEntities();
  $user_entity = array_pop($user_entities);
  if (!empty($user_entity)) {
    $directory_entries = $user_entity->get('field_directory_entry')->referencedEntities();
    $directory_entry = array_pop($directory_entries);
  }

  // Strip the description to cosmetic tags only (no links or media).
  if (!empty($variables['content']['field_description'][0])) {
    breema_strip_links($variables['content']['field_description'][0]['#text']);
  }

  // Container for everything that's a single link (title, media, description).
  $variables['content']['link-target'] = [
    '#type' => 'container',
    '#prefix' => '<a href="' . $variables['url'] . '" class="teaser-link">',
    '#suffix' => '</a>',
    'field_header_text' => $variables['content']['field_header_text'],
    // Nested grid for the media + description for responsive styles.
    'grid' => [
      '#type' => 'container',
      'field_media' => $variables['content']['field_media'],
      'field_description' => $variables['content']['field_description'],
      '#attributes' => [
        'class' => ['grid--container', 'grid--container-1-2u3366'],
      ],
    ],
  ];
  // Hide everything in the main content array to prevent duplicate rendering.
  foreach (['field_header_text', 'field_media', 'field_description'] as $field_name) {
    $variables['content'][$field_name]['#access'] = FALSE;
  }

  $show_upcoming = $variables['paragraph']->get('field_show_upcoming_events')->value;
  if (!empty($show_upcoming)) {
    $display = 'embed_upcoming';
    $view = Views::getView('breema_event_dashboard');
    $view->setDisplay($display);
    if (!empty($user_entity)) {
      $id = $user_entity->id();
      $view->setArguments([$id, $id]);
    }
    $view->execute();
    if (count($view->result)) {
      $variables['content'][$display] = [
        '#weight' => 100,
        '#prefix' => '<h3>' . t('Upcoming events with :name', [':name' => $user_entity->label()]) . '</h3>',
        'content' => $view->preview($display),
      ];
      if (!empty($directory_entry)) {
        $variables['content']['read-more'] = [
          '#weight' => 105,
          '#prefix' => '<div class="more-link">',
          '#markup' => $directory_entry->toLink(t('More events'))->toString(),
          '#suffix' => '</div>',
        ];
      }
    }
  }
}

/**
 * Preprocess function for 'Media: single' paragraph type.
 *
 * Injects the slice's link URL as a template variable.
 */
function breema_preprocess_paragraph__media_single(&$variables) {
}

/**
 * Generate a render array of inline action links to see more Breema events.
 */
function _breema_get_more_events_action_links() {
  $render = [
    '#type' => 'container',
    '#weight' => 100,
    '#attributes' => ['class' => ['container-inline']],
    'header' => [
      '#weight' => -10,
      '#prefix' => '<h3>',
      '#markup' => t('More Breema events'),
      '#suffix' => '</h3>',
    ],
  ];
  $actions = [
    'calendar' => '/events',
    'search' => '/events/search',
    'map' => '/directory?type[]=event',
  ];
  foreach ($actions as $action => $action_path) {
    $url = Url::fromUri('internal:' . $action_path);
    $render[$action] = [
      '#prefix' => '<div class="action-secondary inline">',
      '#markup' => t('<a href=":url">:label</a>', [':url' => $url->toString(), ':label' => Unicode::ucfirst($action)]),
      '#suffix' => '</div>',
    ];
  }
  return $render;
}

/**
 * Implements hook_theme_registry_alter()
 */
function breema_theme_registry_alter(&$theme_registry) {
  $breema_path = drupal_get_path('module', 'breema') . '/templates';
  $theme_registry['field__paragraph__field_book_type'] = [
    'path' => $breema_path,
    'template' => 'field--paragraph--field-book-type',
  ] + $theme_registry['field'];
  $theme_registry['field__paragraph__field_description'] = [
    'path' => $breema_path,
    'template' => 'field--paragraph--field-description',
  ] + $theme_registry['field'];
  $theme_registry['geolocation_common_map_display']['path'] = $breema_path;
  $theme_registry['paragraph__product_info_audio'] = [
    'path' => $breema_path,
    'template' => 'paragraph--product-info-audio',
  ] + $theme_registry['paragraph'];
  $theme_registry['paragraph__product_info_book'] = [
    'path' => $breema_path,
    'template' => 'paragraph--product-info-book',
  ] + $theme_registry['paragraph'];
  $theme_registry['paragraph__product_info_general'] = [
    'path' => $breema_path,
    'template' => 'paragraph--product-info-general',
  ] + $theme_registry['paragraph'];
}

/**
 * Implements hook_views_pre_render().
 */
function breema_views_pre_render(ViewExecutable $view) {
  if (isset($view)) {
    switch($view->storage->id()) {
      case 'breema_directory':
        $view->element['#attached']['library'][] = 'breema/views.breema_directory';
        $view->element['#attached']['library'][] = 'breema/views.geolocation_map';

        $view->element['#attached']['library'][] = 'breema/directory_entry';
        break;

      case 'breema_event_map':
        $view->element['#attached']['library'][] = 'breema/views.geolocation_map';
        break;

      case 'breema_place_browser':
        $view->element['#attached']['library'][] = 'breema/entity-browser';
        break;

      case 'breema_events_by_instructor':
        return breema_views_pre_render_breema_events_by_instructor($view);

      case 'breema_events_by_location':
        return breema_views_pre_render_breema_events_by_location($view);
    }
  }
}

/**
 * Implements hook_views_pre_render() for breema_events_by_instructor.
 *
 * On the 'block_map' display, inject the instructor's directory entry, if any.
 */
function breema_views_pre_render_breema_events_by_instructor(ViewExecutable $view) {
  if ($view->current_display == 'block_map') {
    $user_argument = $view->display_handler->getHandler('argument', 'field_instructors_target_id');
    if (!empty($user_argument)) {
      $instructor = User::load($user_argument->getValue());
      if (!empty($instructor)) {
        $directory_entries = $instructor->get('field_directory_entry')->referencedEntities();
        if (!empty($directory_entries)) {
          $directory_entry = array_pop($directory_entries);
          $result = new ResultRow();
          // Pretend this is the location for an event, since it has all the
          // same fields we need: title, address and geolocation.
          $result->_relationship_entities['field_location'] = $directory_entry;
          $result->index = count($view->result);
          if (empty($view->result)) {
            $gmap_settings = &$view->display_handler->getPlugin('style')->options['google_map_settings'];
            $gmap_settings['width'] = '300px';
            $gmap_settings['height'] = '300px';
            $gmap_settings['maxZoom'] = 10;
          }
          $view->result[] = $result;
        }
      }
    }
  }
}

/**
 * Implements hook_views_pre_render() for breema_events_by_location.
 *
 * Only start doing a grid for upcoming events if there are more than 3.
 */
function breema_views_pre_render_breema_events_by_location(ViewExecutable $view) {
  if ($view->current_display == 'block_1') {
    $settings = &$view->display_handler->getPlugin('style')->options;
    if (count($view->result) < 3) {
      $settings['class'] = 'grid--container'; // not grid--container-1-2
    }
  }
}

/**
 * Implements hook_form_alter()
 *
 * Sets an #after_build callback on media entity forms to hide revision log.
 */
function breema_form_alter(&$form, FormStateInterface $form_state) {
  switch ($form['#form_id']) {
    case 'entity_browser_image_browser_form':
    case 'entity_browser_image_embed_form':
    case 'entity_browser_media_browser_form':
    case 'entity_browser_media_embed_form':
      if (!empty($form['widget'])) {
        $form['widget']['#after_build'][] = 'breema_entity_browser_media_after_build';
      }
      break;
  }
  if (substr($form['#form_id'], 0, 15) == 'entity_browser_') {
    breema_entity_browser_form_alter($form, $form_state);
  }
}

/**
 * Form alter helper for all entity_browser forms.
 *
 * Duplicates the action buttons at the top of the form (to help w/ scrolling).
 */
function breema_entity_browser_form_alter(&$form, FormStateInterface $form_state) {
  if (!empty($form['widget']['view'])) {
    $form['widget']['top_actions'] = $form['widget']['actions'];
    $form['widget']['top_actions']['#weight'] = -10;
  }
}

/**
 * #after_build callback for media inline_entity_form elements.
 *
 * Hides the (totally confusion and pointless) revision log element.
 */
function breema_entity_browser_media_after_build($form_element, FormStateInterface $form_state) {
  if (!empty($form_element['inline_entity_form']['revision_log_message'])) {
    $form_element['inline_entity_form']['revision_log_message']['#access'] = FALSE;
  }
  return $form_element;
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 *
 * Invokes the directory_entry form alter method with the right user entity.
 */
function breema_inline_entity_form_entity_form_alter(&$entity_form, \Drupal\Core\Form\FormStateInterface &$form_state) {
  if ($entity_form['#entity_type'] == 'node' && !empty($entity_form['#bundle']) && $entity_form['#bundle'] == 'directory_entry') {
    $user = $form_state->getFormObject()->getEntity();
    $entity_form['uid']['widget'][0]['target_id']['#default_value'] = $user;
    breema_directory_entry_node_form_alter($entity_form, $form_state, $user, $entity_form['#entity'], TRUE);
  }
  if ($entity_form['#entity_type'] === 'media'
      && !empty($entity_form['#bundle'])
      && $entity_form['#bundle'] === 'file'
  ) {
    breema_file_media_form_alter($entity_form, $form_state);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for 'node_form'.
 */
function breema_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  // Find the appropriate user entity and invoke the shared method.
  if ($node->bundle() == 'directory_entry') {
    $authors = $node->get('uid')->referencedEntities();
    $author = array_pop($authors);
    breema_directory_entry_node_form_alter($form, $form_state, $author, $node, FALSE);
  }
  // Products have a special #after_build callback.
  else if ($node->bundle() == 'product') {
    $form['field_by']['widget'][0]['#after_build'][] = 'breema_product_node_form_after_build';
  }
  // Schedule events (with a parent) can't access their title, require subtitle.
  else if ($node->bundle() == 'event') {
    if (!empty($form['field_parent_event']['widget'][0]['target_id']['#default_value'])) {
      $form['title']['#access'] = FALSE;
      $form['field_subtitle']['widget'][0]['value']['#required'] = TRUE;
    }
    $form['other_website_desc'] = [
      '#markup' => $form['field_website']['widget']['#description'],
      '#prefix' => '<div class="description">',
      '#suffix' => '</div>',
      '#weight' => -10,
    ];
    unset($form['field_website']['widget']['#description']);
    $form['#group_children']['other_website_desc'] = 'group_other_links';
  }
  elseif ($node->bundle() == 'essence') {
    $form['field_source_product']['#states'] = [
      'visible' => [
        ':input[name="field_source_type"]' => ['value' => 'product'],
      ],
    ];
    $form['field_source_other']['#states'] = [
      'visible' => [
        ':input[name="field_source_type"]' => ['value' => 'other'],
      ],
    ];
    $form['#validate'][] = 'breema_essence_node_form_validate';
  }
}

/**
 * Additional validate handler for Essence of Breema node forms.
 */
function breema_essence_node_form_validate($form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  if (!empty($values['field_source_type'][0]['value'])
      && $values['field_source_type'][0]['value'] == 'product'
      && empty($values['field_source_product'][0]['target_id'])
  ) {
    $form_state->setErrorByName('field_source_product', t('If this excerpt is from a book, you must define the product.'));
  }
}

/**
 * Alter a directory_entry node form, regardless of IEF or stand-alone.
 *
 * @param array $form
 *   Reference to the form array to alter.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 * @param \Drupal\user\UserInterface $user
 *   The user entity that the directory entry is attached to.
 * @param \Drupal\node\NodeInterface $directory_entry
 *   The directory entry node entity.
 * @param boolean $is_inline
 *   Is the directory_entry form being rendered inline with the user profile?
 */
function breema_directory_entry_node_form_alter(&$form, FormStateInterface $form_state, UserInterface $user, NodeInterface $directory_entry, $is_inline = FALSE) {
  if ($is_inline) {
    $route = '<current>';
    $route_args = [];
  }
  else {
    $route = 'entity.user.edit_form';
    $route_args = ['user' => $user->id()];
    $url_options['query']['destination'] = Url::fromRoute('<current>')->toString();
  }
  $url_options['fragment'] = 'edit-mail';
  $email_url = Url::fromRoute($route, $route_args, $url_options)->toString();
  $url_options['fragment'] = 'edit-user-contact-wrapper';
  $contact_url = Url::fromRoute($route, $route_args, $url_options)->toString();

  if (!$is_inline) {
    if (!$directory_entry->isPublished()) {
      $form['warning'] = [
        '#type' => 'markup',
        '#markup' => _breema_get_directory_entry_warning('edit-form', $directory_entry),
        '#prefix' => '<div class="messages messages--warning">',
        '#suffix' => '</div>',
        '#weight' => '-100',
      ];
    }
    $url_options['fragment'] = 'edit-user-picture-wrapper';
    $headshot_url = Url::fromRoute($route, $route_args, $url_options)->toString();
    $form['headshot'] = [
      '#type' => 'details',
      '#title' => t('Headshot image'),
      '#open' => TRUE,
      '#weight' => 9,
    ];
    $user_pictures = $user->get('user_picture')->referencedEntities();
    if (!empty($user_pictures)) {
      $user_picture = array_pop($user_pictures);
      $form['headshot']['current'] = [
        '#theme' => 'image_style',
        '#style_name' => 'thumbnail',
        '#weight' => -1,
        '#prefix' => '<div class="headshot">',
        '#suffix' => '</div>',
        '#uri' => $user_picture->getFileUri(),
      ];
      $form['headshot']['help'] = [
        '#type' => 'item',
        '#description' => t('You must <a href=":edit">edit your user account</a> and use the <em>Picture</em> field to manage the image displayed with your directory entry.', [':edit' => $headshot_url]),
      ];
    }
    else {
      $form['headshot']['help'] = [
        '#type' => 'item',
        '#description' => t('If you <a href=":edit">edit your user account</a> you can upload an image in the <em>Picture</em> field and it will be displayed with your directory entry.', [':edit' => $headshot_url]),
      ];
    }
  }

  // If not already defined, set default values for first and last name based
  // on the values in the user entity.
  foreach (['last', 'first'] as $name_type) {
    $field_name = 'field_name_' . $name_type;
    if (empty($form[$field_name]['widget'][0]['value']['#default_value'])) {
      $form[$field_name]['widget'][0]['value']['#default_value'] = $user->get($field_name)->value;
    }
  }
  $author_address = $user->get('field_address')->getValue();
  foreach (
    [
      'country_code',
      'administrative_area',
      'locality',
      'postal_code',
    ] as $addr_field)
  {
    if (empty($form['field_address']['widget'][0]['address']['#default_value'][$addr_field])) {
      $form['field_address']['widget'][0]['address']['#default_value'][$addr_field] = $author_address[0][$addr_field];
    }
  }
  $user_data = \Drupal::service('user.data');
  $user_contact = $user_data->get('contact', $user->id(), 'enabled');
  if ($user_contact) {
    $contact_info_desc = t('Since your contact tab is enabled on your user profile, site visitors will be able to send you a message via this website without being able to see your e-mail address. Only list further information here if you want it to be publicly visible.');
  }
  else {
    $contact_info_desc = t('If you enable your contact tab on your user profile, site visitors would be able to send you a message via this website without being able to see your e-mail address. Anything you put here will be publicly visible.');
  }
  $form['contact_info_desc'] = [
    '#type' => 'markup',
    '#markup' => $contact_info_desc,
    '#weight' => -10,
  ];
  $form['#group_children']['contact_info_desc'] = 'group_contact_info';
}

/**
 * #after_build callback for field_by on product nodes.
 */
function breema_product_node_form_after_build($form_element, FormStateInterface $form_state) {
  $form_element['format']['#access'] = FALSE;
  return $form_element;
}

function breema_form_media_form_alter(&$form, FormStateInterface $form_state) {
  $media = $form_state->getFormObject()->getEntity();
  if ($media->bundle() === 'file') {
    breema_file_media_form_alter($form, $form_state);
  }
}

/**
 * Alter a file media form, regardless of IEF or stand-alone.
 */
function breema_file_media_form_alter(&$form, FormStateInterface $form_state) {
  $form['name']['widget'][0]['value']['#description'] = t('The <em>Name</em> will be used as the link to download the file everywhere it appears on the site. Please choose wisely.');
}

/**
 * Implements hook_form_FORM_ID_alter() for 'user_register_form'.
 *
 * Alter the user form specifically when used as user_register.
 */
function breema_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $form['actions']['submit']['#value'] = t('Apply to the Practitioner Certificate Program');
}

/**
 * Implements hook_form_FORM_ID_alter() for 'user_form'.
 *
 * Use #states for conditional fields based on anatomy requirement choice.
 * Hide the 'completed' option for everyone but admins.
 * Hide various fields unless it's a new user or an admiin.
 */
function breema_form_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $user = $form_state->getFormObject()->getEntity();
  $roles = $user->getRoles();
  $is_certified = (in_array('instructor', $roles) || in_array('practitioner', $roles));

  $current_user = \Drupal::currentUser();
  $current_roles = $current_user->getRoles();
  $is_user_admin = (in_array('administrator', $current_roles) || in_array('user_administrator', $current_roles));

  $form['account']['name']['#required'] = FALSE;
  if ($user->id()) {
    $form['account']['name']['#disabled'] = TRUE;
    $form['account']['name']['#description'] = t("This value is set automatically based on 'First name' and 'Last name' below.");
  }
  else {
    $form['account']['name']['#type'] = 'hidden';
  }
  $form['#validate'][] = 'breema_user_form_validate';

  $form['field_anatomy_homework_language']['#states'] = [
    'visible' => [
      ':input[name="field_anatomy_requirement"]' => ['value' => 'homework'],
    ],
  ];
  // #states doesn't work on a 'details' element, so we use a 'container'.
  $form['field_anatomy_transcript'] = [
    '#type' => 'container',
    '#states' => [
      'visible' => [
        ':input[name="field_anatomy_requirement"]' => ['value' => 'transcript'],
      ],
    ],
    // Now stash the entire existing form element.
    'anatomy_transcript' => $form['field_anatomy_transcript'],
    // Propagate the #weight to retain the right ordering.
    '#weight' => $form['field_anatomy_transcript']['#weight'],
  ];

  if (!empty($form['field_directory_entry']['widget']['entities'][0]['#entity'])) {
    $entity = $form['field_directory_entry']['widget']['entities'][0]['#entity'];
    if (!$entity->isPublished()) {
      $form['field_directory_entry']['widget']['entities']['#prefix'] = '<div class="messages messages--warning">' . _breema_get_directory_entry_warning('ief', $entity) .  '</div>';
    }
  }

  // If the current user is an admin, return now.
  if ($is_user_admin) {
    return;
  }

  // Once a user is authenticated (not the registration form) hide
  // 'why_interested' and 'class_attended'.
  if (in_array('authenticated', $roles)) {
    $form['field_why_interested']['#access'] = FALSE;
    $form['field_class_attended']['#access'] = FALSE;
  }
  // Once certified, hide all the requirement-related fields.
  if ($is_certified) {
    $fields = [
      'field_anatomy_requirement',
      'field_anatomy_transcript',
      'field_anatomy_homework_language',
      'field_class_other',
    ];
    foreach ($fields as $field) {
      $form[$field]['#access'] = FALSE;
    }
  }
  // Otherwise, don't let students set themselves to 'complete'.
  else {
    unset($form['field_anatomy_requirement']['widget']['#options']['complete']);
    // Also, hide the directory_entry field for everyone not certified.
    $form['field_directory_entry']['#access'] = FALSE;
  }
}

/**
 * Implements hook_validation_constraint_alter().
 *
 * Override core NotNull constraint to allow entities that use Auto Entity
 * Labels to validate when their label is empty before being set automatically.
 */
function breema_validation_constraint_alter(array &$definitions) {
  $definitions['UserName']['class'] = 'Drupal\breema\Plugin\Validation\Constraint\BreemaUserNameConstraint';
}

/**
 * Additional validate handler for user_form().
 */
function breema_user_form_validate($form, FormStateInterface $form_state) {
  $user_entity = $form_state->getFormObject()->getEntity();
  $values = $form_state->getValues();
  $first_name = trim($values['field_name_first'][0]['value']);
  $last_name = trim($values['field_name_last'][0]['value']);
  $user_name = $first_name . ' ' . $last_name;
  $name_in_use = (bool) \Drupal::entityQuery('user')
    ->condition('uid', (int)$user_entity->id(), '<>')
    ->condition('name', $user_name, '=')
    ->range(0, 1)
    ->count()
    ->execute();
  if ($name_in_use) {
    $form_state->setErrorByName('field_name_first', t('Sorry, this name is already taken. Please add a middle initial to your first name.'));
  }
  $form_state->setValueForElement(['#parents' => ['name']], $user_name);
  // Force the first/last names to the trimmed copies.
  $form_state->setValueForElement(['#parents' => ['field_name_first', 0, 'value']], $first_name);
  $form_state->setValueForElement(['#parents' => ['field_name_last', 0, 'value']], $last_name);
}

/**
 * Implements hook_form_FORM_ID_alter() for 'views_exposed_form'.
 *
 * Sets more sane sizes for the various text field exposed filters.
 */
function breema_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $filter_sizes = [
    'postal_code' => 10,
    'telephone' => 15,
    'email' => 20,
    'city' => 20,
    'job_title' => 20,
    'search' => 20,
  ];
  foreach ($filter_sizes as $key => $size) {
    if (!empty($form[$key])) {
      $form[$key]['#size'] = $size;
    }
  }

  if (!empty($form['geolocation_op'])) {
    $form['geolocation_op']['#title'] = t('Geolocation');
    $form['geolocation_op']['#options'] = [
      ' ' => t('- Any -'),
      'not empty' => t('Defined'),
      'empty' => t('Undefined'),
    ];
    $form['geolocation_op']['#default_value'] = ' ';
  }

  // Completely hide the boundary filters so they don't flicker on JS loading.
  if (!empty($form['boundary'])) {
    foreach (Element::children($form['boundary']) as $key) {
      $form['boundary'][$key]['#type'] = 'hidden';
    }
  }

  if (!empty($form['country'])) {
    $breema_countries = \Drupal::state()->get('breema.breema_countries', []);
    if (empty($breema_countries)) {
      $query = \Drupal::database()->select('node__field_address', 'nfa');
      $query->addField('nfa', 'field_address_country_code');
      $query->distinct();
      $results = array_filter($query->execute()->fetchCol());
      $breema_countries = array_combine($results, $results);
      \Drupal::state()->set('breema.breema_countries', $breema_countries);
    }

    $country_list = array_keys($form['country']['#options']);
    foreach ($country_list as $country) {
      if ($country != 'All' && empty($breema_countries[$country])) {
        unset($form['country']['#options'][$country]);
      }
    }
  }

  if (!empty($form['end_datetime_op'])) {
    $form['end_datetime_op']['#title'] = t('Date/time');
    $form['end_datetime_op']['#options'] = [
      'not empty' => t('- Any -'),
      '>=' => t('Upcoming'),
      '<=' => t('Past'),
    ];
    $form['end_datetime']['#access'] = FALSE;
  }

  $view = $form_state->getStorage('view');
  switch ($view['view']->id()) {
    case 'media':
    case 'media_entity_browser':
      $media_types = [
        'file' => 'file_type',
        'image' => 'image_type',
        'video' => 'video_type',
      ];
      foreach ($media_types as $type_name => $type_element) {
        if (!empty($form['type']) && !empty($form[$type_element])) {
          $form[$type_element]['#states'] = [
            'visible' => [
              ':input[name="type"]' => ['value' => $type_name],
            ],
          ];
        }
      }
      if (!empty($form['langcode'])) {
        $form['langcode']['#access'] = FALSE;
      }
      break;

    case 'breema_directory':
      $form['type']['#options'] = [
        'event' => t('Event'),
        'directory_entry' => t('Person'),
      ];
      $form['certification']['#options'] = [
        'practitioner' => t('Breema Practitioner'),
        'inst-self-breema' => t('Self-Breema Instructor'),
        'inst-breema' => t('Breema Instructor'),
      ];
      break;

  }
}

/**
 * Implements hook_form_FORM_ID_alter() for 'user_login_form'.
 *
 * Remove unneeded #description text and fix #title for 'name' element.
 */
function breema_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['name']['#title'] = t('Username or email address');
  $form['name']['#description'] = '';
  $form['pass']['#description'] = '';
}

/**
 * Implements hook_entity_type_alter().
 */
function breema_entity_type_alter(array &$entity_types) {
  $entity_types['node']->setLinkTemplate('clone-form', '/node/{node}/clone');
  $entity_types['node']->setLinkTemplate('add-schedule-form', '/node/{node}/add-schedule');
}

/**
 * Implements hook_entity_operation().
 */
function breema_entity_operation(EntityInterface $entity) {
  $operations = [];
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'event') {
    $operations['clone_form'] = [
      'title' => t('Clone'),
      'url' => $entity->toUrl('clone-form'),
      'weight' => 50,
    ];
    if (empty($entity->get('field_parent_event')->getValue())) {
      $operations['add_schedule_form'] = [
        'title' => t('Add schedule'),
        'url' => $entity->toUrl('add-schedule-form'),
        'weight' => 40,
      ];
    }
  }
  return $operations;
}

/**
 * Implements hook_ENTITY_TYPE_insert() as hook_node_insert().
 */
function breema_node_insert(NodeInterface $node) {
  breema_node_cud($node, 'insert');
}

/**
 * Implements hook_ENTITY_TYPE_update() as hook_node_update().
 */
function breema_node_update(NodeInterface $node) {
  breema_node_cud($node, 'update');
}

/**
 * Implements hook_ENTITY_TYPE_delete() as hook_node_delete().
 */
function breema_node_delete(NodeInterface $node) {
  breema_node_cud($node, 'delete');
}

/**
 * Shared code invoked on any node CUD (Create, Update, Delete) operation.
 *
 * Invokes bundle-specific helper functions.
 */
function breema_node_cud(NodeInterface $node, $operation) {
  switch ($node->bundle()) {
    case 'directory_entry':
      breema_node_cud__directory_entry($node, $operation);
      break;

    case 'event':
      breema_node_cud__event($node, $operation);
      break;

    case 'place':
      breema_node_cud__place($node, $operation);
      break;

  }
}

/**
 * Callback invoked for any directory_entry node CUD operation.
 *
 * Clears the list of Breema countries when touching any directory entry.
 *
 * Also keeps field_directory_entry (on the user entity) consistent for the
 * owner of any directory entry node.
 */
function breema_node_cud__directory_entry(NodeInterface $node, $operation) {
  \Drupal::state()->delete('breema.breema_countries');
  $uid = $node->getOwnerId();
  $account = User::load($uid);
  if (!empty($account)) {
    $account->set('field_directory_entry', $operation == 'delete' ? NULL : $node->id());
    $account->save();
  }
}

/**
 * Callback invoked for any event node CUD (Create, Update, Delete) operation.
 *
 * Retest (and if needed, update) field_has_active_event and
 * field_upcoming_events on all place and directory entry nodes.
 *
 * Ensure that the location is added to 'My places' for all instructors.
 */
function breema_node_cud__event(NodeInterface $node, $operation) {
  $event_mgr = new BreemaEventMgr();
  $event_mgr->update();

  $instructors = $node->get('field_instructors')->getValue();
  if ($operation != 'delete' && !empty($instructors)) {
    $places = $node->get('field_location')->referencedEntities();
    if (!empty($places)) {
      $place = array_pop($places);
      foreach ($instructors as $instructor) {
        breema_ensure_flag('my_places', $place, $instructor['target_id']);
      }
    }
  }
}

/**
 * Callback invoked for any place node CUD (Create, Update, Delete) operation.
 *
 * Ensure that the location is added to 'My places' for the owner.
 *
 * Update the address and geolocation on any event nodes pointing to this place
 * that don't match the current value.
 */
function breema_node_cud__place(NodeInterface $node, $operation) {
  if ($operation != 'delete') {
    breema_ensure_flag('my_places', $node, $node->getOwnerId());
  }

  $query = \Drupal::entityQuery('node');
  $query
    ->condition('type', 'event')
    ->condition('field_location', $node->id());
  $results = $query->execute();
  if (!empty($results)) {
    $events = Node::loadMultiple($results);
  }
  $address = $operation == 'delete' ? [] : $node->get('field_address')->getValue();
  $geolocation = $operation == 'delete' ? [] : $node->get('field_geolocation')->getValue();
  if (!empty($events)) {
    foreach ($events as $event) {
      $cur_address = $event->get('field_address')->getValue();
      $cur_geolocation = $event->get('field_geolocation')->getValue();
      if ($address != $cur_address || $geolocation != $cur_geolocation) {
        $event->set('field_address', $address);
        $event->set('field_geolocation', $geolocation);
        $event->save();
      }
    }
  }
}

/**
 * Ensure that the given user has flagged the given node with the given flag.
 */
function breema_ensure_flag($flag_id, NodeInterface $node, $uid) {
  static $existing_flag_uids = [];
  $flag = \Drupal::service('flag')->getFlagById($flag_id);
  if (empty($existing_flag_uids[$node->id()])) {
    $flaggings = \Drupal::service('flag')->getEntityFlaggings($flag, $node);
    foreach ($flaggings as $flagging) {
      $existing_flag_uids[$node->id()][$flagging->getOwnerId()] = TRUE;
    }
  }
  if (empty($existing_flag_uids[$node->id()][$uid])) {
    $values = [
      'flag_id' => $flag_id,
      'entity_type' => 'node',
      'entity_id' => $node->id(),
      'flagged_entity' => $node->id(),
      'uid' => $uid
    ];
    $flagging = \Drupal::entityManager()->getStorage('flagging')->create($values);
    $flagging->save();
    $existing_flag_uids[$node->id()][$uid] = TRUE;
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for node entities.
 *
 * Denormalize the address and geolocation from the place into the event.
 * On schedule (child) events, set title based on subtitle and parent title.
 */
function breema_node_presave(NodeInterface $node) {
  if ($node->bundle() == 'event') {
    $places = $node->get('field_location')->referencedEntities();
    if (!empty($places)) {
      $place = array_pop($places);
      $address = $place->get('field_address')->getValue();
      $geolocation = $place->get('field_geolocation')->getValue();
      $node->set('field_address', $address);
      $node->set('field_geolocation', $geolocation);
    }

    $parent_value = $node->get('field_parent_event')->getValue();
    if (!empty($parent_value)) {
      $parent_events = $node->get('field_parent_event')->referencedEntities();
      $parent_event = array_pop($parent_events);
      $title = $node->get('field_subtitle')->value . ' - ' . $parent_event->label();
      $node->setTitle($title);
    }
  }
  elseif ($node->bundle() == 'directory_entry') {
    $authors = $node->get('uid')->referencedEntities();
    if (!empty($authors)) {
      $author_entity = array_pop($authors);
      $author_fields = [
        'field_certification',
        'field_breema_center_staff',
        'field_breema_clinic_practitioner',
      ];
      foreach ($author_fields as $field) {
        $value = $author_entity->get($field)->getValue();
        $node->set($field, $value);
      }
    }
  }
}

/**
 * Implements hook_entity_create_access().
 */
function breema_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  $user = \Drupal\user\Entity\User::load($account->id());
  if (!$user->hasRole('content_administrator')
      && $context['entity_type_id'] == 'node'
      && $entity_bundle == 'directory_entry')
  {
    // Deny creation if this user already owns a directory entry node.
    $directory_entry = $user->get('field_directory_entry')->getValue();
    if (!empty($directory_entry)) {
      return AccessResult::forbidden();
    }
  }
  return AccessResult::neutral();
}

/**
 * Creates a merged title with the main title and optional subtitle.
 */
function breema_merge_titles(\Drupal\node\NodeInterface $node) {
  $merged_title = '';
  if ($node->hasField('field_title_main')) {
    $main_title = $node->get('field_title_main')->getValue();
    $merged_title = $main_title[0]['value'];
    if ($node->hasField('field_title_sub')) {
      $subtitle = $node->get('field_title_sub')->getValue();
      if (!empty($subtitle)) {
        $merged_title .= ': ' . $subtitle[0]['value'];
      }
    }
  }
  return $merged_title;
}

/**
 * Generate a render array of action links for a directory entry.
 *
 * @param \Drupal\node\Entity\NodeInterface $directory_entry
 *   The fully-loaded directory entry node entity, or NULL if there is none.
 * @param boolean $include_create_link
 *   Should the action links contain a link to create an entry (if appropriate)?
 * @return array
 *   Appropriate render array for the current user and given directory entry.
 */
function _breema_get_directory_entry_action_links(NodeInterface $directory_entry = NULL, $include_create_link = FALSE) {
  $current_page = Url::fromRoute('<current>');
  $url_options['query']['destination'] = $current_page->toString();

  // If there's no entry and we don't want create links, bail now.
  if (empty($directory_entry) && !$include_create_link) {
    return [];
  }

  // If there's no entry, and the user has permission, add links to create one.
  if (empty($directory_entry)) {
    $current_user = \Drupal::currentUser();
    $node_type = NodeType::load('directory_entry');
    $result = \Drupal::service('access_check.node.add')->access($current_user, $node_type);
    if ($result) {
      $directory_url = Url::fromUri('base:/directory');
      $add_entry_url = Url::fromRoute('node.add', ['node_type' => 'directory_entry'], $url_options);
      return [
        'note' => [
          '#prefix' => '<p>',
          '#markup' => t('You do not have an entry in the <a href=":breema-directory">International Breema directory</a>.', [':breema-directory' => $directory_url->toString()]),
          '#suffix' => '</p>',
        ],
        'add-link' => [
          '#prefix' => '<div class="action">',
          '#markup' => t('<a href=":create-directory-entry" target="_blank">Create entry</a>', [':create-directory-entry' => $add_entry_url->toString()]),
          '#suffix' => '</div>',
        ],
      ];
    }
  }

  // Otherwise, generate whatever links the user has permission to use.
  $links = [];
  if ($directory_entry->access('update')) {
    $edit_url = Url::fromRoute('entity.node.edit_form', ['node' => $directory_entry->id()], $url_options);
    $links['edit-link'] = [
      '#prefix' => '<div class="action-secondary">',
      '#markup' => t('<a href=":edit" target="_blank">Edit</a>', [':edit' => $edit_url->toString()]),
      '#suffix' => '</div>',
    ];
  }
  if ($directory_entry->access('delete')) {
    $delete_url = Url::fromRoute('entity.node.delete_form', ['node' => $directory_entry->id()], $url_options);
    $links['delete-link'] = [
      // For reasons that aren't yet clear, #prefix and #suffix aren't
      // working for this, so we directly stuff those into #markup.
      '#markup' => '<div class="danger">' . t('<a href=":delete" class="danger" target="_blank">Delete</a>', [':delete' => $delete_url->toString()]) . '</div>',
    ];
  }
  return $links;
}

/**
 * Implements hook_entity_view_alter().
 */
function breema_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() == 'user') {
    return breema_entity_user_view_alter($build, $entity, $display);
  }
  if ($entity->getEntityTypeId() == 'node') {
    if ($entity->bundle() == 'directory_entry') {
      return breema_entity_node_directory_entry_view_alter($build, $entity, $display);
    }
    // Special handling for 'Breema and the Nine Principles' page:
    elseif ($entity->id() == 3) {
      return breema_node_3_view_alter($build, $entity, $display);
    }
  }
}

/**
 * Callback for hook_entity_view_alter() for user entities.
 */
function breema_entity_user_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $current_user = \Drupal::currentUser();
  $current_roles = $current_user->getRoles();
  $is_user_admin = (in_array('administrator', $current_roles) || in_array('user_administrator', $current_roles));
  if (!$is_user_admin) {
    $fields = [
      'field_anatomy_requirement',
      'field_anatomy_transcript',
      'field_anatomy_homework_language',
      'field_class_attended',
      'field_class_other',
      'field_why_interested',
    ];
    foreach ($fields as $field) {
      $build[$field]['#access'] = FALSE;
    }
  }
  // Private fields that users (admins) should see (but not touch):
  $can_see = $is_user_admin || $entity->id() == $current_user->id();
  $private_fields = [
    'member_for',
    'field_breema_center_staff',
    'field_breema_clinic_practitioner',
    'field_certification',
  ];
  foreach ($private_fields as $field) {
    $build[$field]['#access'] = $can_see;
  }
  if ($display->getMode() == 'default') {
    $user_roles = $entity->getRoles();
    $is_certified = (in_array('instructor', $user_roles) || in_array('practitioner', $user_roles));
    if ($is_certified) {
      $directory_entries = $entity->get('field_directory_entry')->referencedEntities();
      $directory_entry = !empty($directory_entries) ? array_pop($directory_entries) : NULL;
      $can_create = $current_user->id() == $entity->id();
      $build['action_links'] = _breema_get_directory_entry_action_links($directory_entry, $can_create);
      $build['action_links']['#weight'] = 10;
      $build['#group_children']['action_links'] = 'group_public_directory_entry';
      if (!empty($directory_entry) && !$directory_entry->isPublished()) {
        $build['warning'] = [
          '#type' => 'markup',
          '#markup' => _breema_get_directory_entry_warning('block', $directory_entry),
          '#prefix' => '<div class="messages messages--warning">',
          '#suffix' => '</div>',
          '#weight' => '-100',
        ];
        $build['#group_children']['warning'] = 'group_public_directory_entry';
      }
    }
    // @todo fix cache contexts/tags/etc.
  }
}

/**
 * Callback for hook_entity_view_alter() for user entities.
 */
function breema_entity_node_directory_entry_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // @todo fix cache contexts/tags/etc.
  $build['#attached']['library'][] = 'breema/directory_entry';
  $author = $build['#node']->get('uid')->getValue();
  if (!empty($author[0]['target_id'])) {
    $author_uid = $author[0]['target_id'];
  }
  if (!empty($author_uid)) {
    $access_manager = \Drupal::service('access_manager');
    if ($access_manager->checkNamedRoute('entity.user.contact_form', ['user' => $author_uid])) {
      $contact_url = Url::fromRoute('entity.user.contact_form', ['user' => $author_uid]);
    }
    $author_entity = user_load($author_uid);
    $user_picture = $author_entity->get('user_picture')->getValue();
  }

  if (!empty($user_picture[0]['target_id'])) {
    $user_picture_file = file_load($user_picture[0]['target_id']);
    if (!empty($user_picture_file)) {
      $build['headshot'] = [
        '#theme' => 'image_style',
        '#style_name' => $build['#view_mode'] == 'full' ? 'medium' : 'thumbnail',
        '#weight' => -1,
        '#prefix' => '<div class="headshot">',
        '#suffix' => '</div>',
        '#uri' => $user_picture_file->getFileUri(),
        '#alt' => t('Profile image for @user_name', ['@user_name' => $author_entity->getAccountName()]),
      ];
      if ($build['#view_mode'] == 'teaser_compact' || $build['#view_mode'] == 'teaser_search_result') {
        $build['headshot']['#prefix'] .= '<a href="' . $entity->toUrl()->toString() . '">';
        $build['headshot']['#suffix'] = '</a></div>';
      }
    }
  }

  if (!empty($contact_url) && ($build['#view_mode'] == 'full' || $build['#view_mode'] == 'teaser_search_result')) {
    $build['contact_link'] = [
      '#weight' => 6,
      '#prefix' => '<div class="contact-form-link">',
      '#markup' => t('<a href=":contact">Send message</a>', [':contact' => $contact_url->toString()]),
      '#suffix' => '</div>',
    ];
  }

  // Inject a 'Read more' link at the end of the upcoming events list.
  if ($build['#view_mode'] == 'teaser_search_result'
      && !empty($build['field_upcoming_events']['#items'])
  ) {
    $item_count = count($build['field_upcoming_events']['#items']);
    $build['field_upcoming_events'][$item_count] = [
      '#type' => 'markup',
      '#markup' => $entity->toLink(t('Read more'))->toString(),
    ];
  }

  if ($build['#view_mode'] == 'full' && !$entity->isPublished()) {
    $build['warning'] = [
      '#type' => 'markup',
      '#markup' => _breema_get_directory_entry_warning('block', $entity),
      '#prefix' => '<div class="messages messages--warning">',
      '#suffix' => '</div>',
      '#weight' => '-100',
    ];
  }
}

/**
 * Callback for hook_entity_view_alter() for user entities.
 */
function breema_node_3_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($display->getMode() == 'default') {
    $view = Views::getView('breema_nine_principles');
    $view->setDisplay('embed_1');
    $view->execute();
    $build['teasers'] = $view->preview();
    $build['field_main_image']['#weight'] = -1;
    $build['body']['#weight'] = 0;
    $build['teasers']['#weight'] = 1;
    $build['field_resources']['#weight'] = 2;
  }
}

/**
 * Implements hook_cron().
 *
 * Retest (and if needed, update) field_has_active_event and
 * field_upcoming_events on all place and directory entry nodes.
 */
function breema_cron() {
  $event_mgr = new BreemaEventMgr();
  $event_mgr->update();
}

/**
 * Returns an appropriate label given an array of entities.
 *
 * If there's only 1 entity, return the label.
 * If 2, use "LabelA and LabelB".
 * If 3 or more "Label1, ... LabelN-1 and LabelN".
 *
 * @param array $entities
 *   An array of objects that implement \Drupal\Core\Entity\EntityInterface.
 * @param callable $label_callback
 *   A function that takes an object that implements EntityInterface and
 *   returns the appropriate text or markup for the label for that Entity.
 *
 * @return string
 *   Label for all the entities with appropriate delimiter(s) depending on number.
 */
function breema_get_entity_label_multiple(array $entities, $label_callback) {
  $text = '';
  $last = array_pop($entities);
  $last_label = $label_callback($last);
  $text = implode(', ', array_map($label_callback, $entities));
  if (!empty($text)) {
    $text .= " and $last_label";
  }
  else {
    $text = $last_label;
  }
  return $text;
}

/**
 * Label callback to return the plain entity label.
 */
function breema_entity_label_plain(EntityInterface $entity) {
  return $entity->label();
}

/**
 * Label callback to return the entity label as a link to the entity.
 */
function breema_entity_label_link(EntityInterface $entity) {
  return $entity->toLink()->toString();
}

/**
 * Label callback to return a link to an instructor's directory entry.
 */
function breema_entity_label_instructor_directory_entry(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'user') {
    $directory_entries = $entity->get('field_directory_entry')->referencedEntities();
    if (!empty($directory_entries)) {
      $directory_entry = array_pop($directory_entries);
      return $directory_entry->toLink()->toString();
    }
  }
  return $entity->label();
}

/**
 * Private helper method to load breema.install and invoke a DB update.
 */
function _breema_run_update($update_number) {
  require_once drupal_get_path('module', 'breema') . '/breema.install';
  $function = '_breema_update_' . $update_number;
  if (function_exists($function)) {
    $function();
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function breema_local_tasks_alter(&$local_tasks) {
  $local_tasks['user.register']['title'] = (string)t('Apply to the Practitioner Certificate Program');
  $local_tasks['user.register']['weight'] = 100;
}

/**
 * Generate the right warning message for an unpublished directory entry.
 *
 * @param string $warning_context
 *   Context for where the warning is being put, and what instructions to use.
 *   Valid values: 'ief', 'block', 'edit-form'.
 * @return \Drupal\Core\StringTranslation\TranslatableMarkup
 */
function _breema_get_directory_entry_warning($warning_context, NodeInterface $entity) {
  $urls = [
    '@directory_url' => Url::fromUri('base:/directory')->toString(),
    '@delete_url' => $entity->toUrl('delete-form')->toString(),
  ];
  switch ($warning_context) {
    case 'ief':
      return t('Your directory entry is currently not published. To review and publish:<ol><li>Click the "Edit" button in this table.</li><li>Let the directory entry form load.</li><li>Review (and if needed, update) all the information.</li><li>Select the "Published" checkbox near the bottom of the form.</li><li>Click "Update Directory entry" to save the changes and hide this message.</li><li>Scroll to the bottom of this page and click "Save" to make your changes permanent.</li></ol>Alternately, you can use the "Remove" button to delete your entry entirely, but then you will not be listed in the <a href="@directory_url">International Breema Directory</a>.',
$urls);

    case 'block':
      $urls['@edit_url'] = $entity->toUrl('edit-form')->toString();
      return t('Your directory entry is currently not published. To review and publish:<ol><li>Click the <a href="@edit_url">Edit</a> button.</li><li>Let the directory entry form load.</li><li>Review (and if needed, update) all the information.</li><li>Select the "Published" checkbox near the bottom of the form.</li><li>Click "Save" to save the changes and hide this message.</li></ol>Alternately, you can use the <a href="@delete_url">Delete</a> link to remove your listing entirely, but then you will not be listed in the <a href="@directory_url">International Breema Directory</a>.', $urls);

    case 'edit-form':
      return t('Your directory entry is currently not published. To review and publish:<ol><li>Review (and if needed, update) all the information below.</li><li>Select the "Published" checkbox near the bottom of the form.</li><li>Click "Save" to save the changes and hide this message.</li></ol>Alternately, you can use the <a href="@delete_url">Delete</a> link to remove your entry entirely, but then you will not be listed in the <a href="@directory_url">International Breema Directory</a>.', $urls);

  }
}

/**
 * Strip all non-cosmetic HTML tags from a given string.
 *
 * @param string &$text_field
 *   Reference to the string to strip.
 */
function breema_strip_links(&$text_field) {
  $text_field = strip_tags(
    $text_field,
    '<p><em><i><strong><b><ul><ol><li><blockquote><h3><h4><h5><h6><ins><del><dl><dt><dd><cite><br><figure><figcaption>'
  );
}
